spring.application.name=product-order-service

# PostgreSQL settings
spring.datasource.url=jdbc:postgresql://localhost:5432/orderdb
spring.datasource.username=postgres
spring.datasource.password=passport1

# JPA settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Server port
server.port=8080

# Swagger UI Config (if needed)
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

# AWS Configuration
aws.region=eu-north-1
aws.access-key-id=${AWS_ACCESS_KEY_ID}
aws.secret-access-key=${AWS_SECRET_ACCESS_KEY}

# S3 Configuration
aws.s3.bucket-name=product-order-invoices

# SQS Configuration  
aws.sqs.queue-url=https://sqs.eu-north-1.amazonaws.com/079910998608/order-updates-queue

# DynamoDB Configuration
aws.dynamodb.table-name=OrderEvents

# Actuator for health checks
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always